{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "byo-addons-operator.serviceAccountName" . }}
  namespace: {{ include "byo-addons-operator.namespace" . }}
  labels:
    {{- include "byo-addons-operator.labels" . | nindent 4 }}
{{- end }}
