{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "byo-addons-operator.fullname" . }}-metrics
  namespace: {{ include "byo-addons-operator.namespace" . }}
  labels:
    {{- include "byo-addons-operator.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  selector:
    app.kubernetes.io/name: {{ include "byo-addons-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: controller
  ports:
  - name: metrics
    port: {{ .Values.metrics.port }}
    targetPort: metrics
{{- end }}
