apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: byo-addons-controller-manager
  namespace: byo-addons-system
  labels:
    app.kubernetes.io/name: byo-addons
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: byo-addons
      app.kubernetes.io/component: controller
  endpoints:
  - port: metrics
    path: /metrics
