//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *AddonSet) DeepCopyInto(out *AddonSet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *AddonSet) DeepCopy() *AddonSet {
	if in == nil {
		return nil
	}
	out := new(AddonSet)
	in.DeepCopyInto(out)
	return out
}

func (in *AddonSet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AddonSetList) DeepCopyInto(out *AddonSetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		inItems, outItems := &in.Items, &out.Items
		*outItems = make([]AddonSet, len(*inItems))
		for i := range *inItems {
			(*inItems)[i].DeepCopyInto(&(*outItems)[i])
		}
	}
}

func (in *AddonSetList) DeepCopy() *AddonSetList {
	if in == nil {
		return nil
	}
	out := new(AddonSetList)
	in.DeepCopyInto(out)
	return out
}

func (in *AddonSetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AddonSetSpec) DeepCopyInto(out *AddonSetSpec) {
	*out = *in
	if in.Components != nil {
		inComponents, outComponents := &in.Components, &out.Components
		*outComponents = make([]AddonComponent, len(*inComponents))
		for i := range *inComponents {
			(*inComponents)[i].DeepCopyInto(&(*outComponents)[i])
		}
	}
}

func (in *AddonSetSpec) DeepCopy() *AddonSetSpec {
	if in == nil {
		return nil
	}
	out := new(AddonSetSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *AddonSetStatus) DeepCopyInto(out *AddonSetStatus) {
	*out = *in
	if in.Components != nil {
		inComponents, outComponents := &in.Components, &out.Components
		*outComponents = make([]AddonComponentStatus, len(*inComponents))
		for i := range *inComponents {
			(*inComponents)[i].DeepCopyInto(&(*outComponents)[i])
		}
	}
	if in.Conditions != nil {
		inConditions, outConditions := &in.Conditions, &out.Conditions
		*outConditions = make([]metav1.Condition, len(*inConditions))
		for i := range *inConditions {
			(*inConditions)[i].DeepCopyInto(&(*outConditions)[i])
		}
	}
}

func (in *AddonSetStatus) DeepCopy() *AddonSetStatus {
	if in == nil {
		return nil
	}
	out := new(AddonSetStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *AddonComponent) DeepCopyInto(out *AddonComponent) {
	*out = *in
	in.Values.DeepCopyInto(&out.Values)
}

func (in *AddonComponent) DeepCopy() *AddonComponent {
	if in == nil {
		return nil
	}
	out := new(AddonComponent)
	in.DeepCopyInto(out)
	return out
}

func (in *AddonComponentStatus) DeepCopyInto(out *AddonComponentStatus) {
	*out = *in
	in.UpdatedAt.DeepCopyInto(&out.UpdatedAt)
}

func (in *AddonComponentStatus) DeepCopy() *AddonComponentStatus {
	if in == nil {
		return nil
	}
	out := new(AddonComponentStatus)
	in.DeepCopyInto(out)
	return out
}
